### PR TITLE
Update to uproot4 in reference value

### PR DESCRIPTION
**Pull request by mayou36**
Since the python lessons in the starterkit will be updated to uproot4, we also want to have it here

### CODE REVIEW

**Comment by mayou36** [comment]
Hi all, can this be merged?

**Comment by eduardo-rodrigues** [comment]
Seems fair to me at this stage!

**Comment by mayou36** [comment]
Many thanks, can you merge? I don't have the rights

**Comment by eduardo-rodrigues** [comment]
I see @chrisburr is the author so let's give him a bit to react. Othewise I will happily merge since the MR is clearly good. Seems the right approach :-).

**Pull request merged**
